# Generated by Django 5.2.6 on 2025-09-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(unique=True)),
                ('type', models.CharField(choices=[('entertainment', 'Entertainment'), ('learning', 'Learning'), ('utility', 'Utility'), ('education', 'Education')], default='utility', max_length=50)),
                ('paid', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
